### ISSUE TITLE
New versions are missing on hex.pm

### ISSUE THREAD

**Issue by rbino** [dukesoferl/re2#49]
Hi,
I was trying to fix a compilation issue with [CQEx](https://github.com/matehat/cqex) (that in turn uses [cqerl](https://github.com/matehat/cqerl)) and I've noticed that Mix fails to pull `re2` after https://github.com/matehat/cqerl/issues/158 since version 1.9.1 is not published on hex.pm (last published version is 1.8.9).

Can you please publish all the latest versions? Thanks in advance.

**Comment by tuncer** [comment]
Releases published by @rbino, closing
